export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD";
export const SET_ORDER_TYPE = "SET_ORDER_TYPE";